[package]
name = "dinovit_infer"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.23", features = ["derive"] }
image = { version = "0.25.2", default-features = false, features = ["jpeg", "png"] }
itertools = { version = "0.14" }
tch = { version = "0.18.1", features = ["download-libtorch"] }
smallvec = { version = "1.13", features = ["const_generics"] }
