[package]
name = "dinovit_infer"
version = "0.1.0"
edition = "2021"

[dependencies]
candle-core = { git = "https://github.com/huggingface/candle.git", version = "0.8.1" }
candle-nn = { git = "https://github.com/huggingface/candle.git", version = "0.8.1" }
candle-transformers = { git = "https://github.com/huggingface/candle.git", version = "0.8.1" }
clap = { version = "4.5.23", features = ["derive"] }
image = { version = "0.25.2", default-features = false, features = ["jpeg", "png"] }
