use std::error::Error;
use tch::{CModule, Device, IValue, Tensor};

use crate::io;

/// Each DINOv2 patch is 14x14
pub const PATCH_DIM: i64 = 14;

/// - CLS for dinov2
pub const DINOV2_EMBEDDINGS_OFFSET: i64 = 1;

/// - CLS + 4*REG for dinov2-with-registers
pub const DINOV2_WITH_REG_EMBEDDINGS_OFFSET: i64 = 1 + 4;

pub struct ModelResult {
    pub patches: (i64, i64),
    pub image: Tensor,
    pub features: Tensor,
    pub last_hidden_state: Tensor,
}

fn infer(image: &Tensor, model: &CModule) -> Result<(Tensor, Tensor), Box<dyn Error>> {
    let output = model.forward_is(&[IValue::Tensor(image.shallow_clone())])?;
    let mut results = match output {
        IValue::Tuple(elements) if elements.len() == 2 => elements,
        _ => return Err("expected (last_hidden_state, pooler_output)".into()),
    };

    let mut results = results.drain(..);

    match (results.next(), results.next()) {
        (Some(IValue::Tensor(last_hidden_state)), Some(IValue::Tensor(pooler_output))) => {
            Ok((last_hidden_state, pooler_output))
        }
        _ => Err("expected 2-tuple of tensors".into()),
    }
}

fn scaled_result(pooler_output: &Tensor) -> Tensor {
    let scaled_norm = pooler_output.norm().pow_tensor_scalar(-1);
    pooler_output.multiply(&scaled_norm)
}

pub fn get_model_result<R>(
    image: R,
    image_scale: i64,
    model: &CModule,
    device: Device,
) -> Result<ModelResult, Box<dyn Error>>
where
    R: std::io::Read + std::io::Seek,
{
    // Get image and and dimensions for calculation.
    let image = io::load_image(image, device)?;

    // Features are unstable across different global scales, and
    // somewhat stable across dimensional scales.
    //
    // Use 18 (252x252) instead of 16 (224x224) to produce a more detailed
    // result and attention map at almost exactly the same computational cost.
    //
    // It is possible for highly non-square models to have meaningful feature extraction,
    // but in practice it makes no difference identifying scales which keep the aspect
    // ratio, and does not produce feature vectors which are similar enough to identify
    // crops.
    let patches = (18 * image_scale, 18 * image_scale);

    // Scale image into appropriate shape.
    let image = io::resize_image_by_patch_count(image, patches, PATCH_DIM);

    // The pooler output is the [CLS] token generated by the model.
    // It contains high-quality, robust features from the input image.
    let (last_hidden_state, pooler_output) = infer(&image, model)?;

    Ok(ModelResult {
        patches,
        image,
        features: scaled_result(&pooler_output.squeeze()),
        last_hidden_state,
    })
}

fn into_principal_components(data: &Tensor, q: i64) -> Result<Tensor, Box<dyn Error>> {
    let mean = data.mean_dim(0, false, None);
    let centered_data = data.f_sub(&mean)?;
    let (_u, _s, v) = centered_data.svd(true, true);

    Ok(centered_data.matmul(&v.slice(1, 0, q, 1)))
}

pub fn visualize_attention(
    last_hidden_state: &Tensor,
    embeddings_offset: i64,
    size: (i64, i64),
) -> Result<Tensor, Box<dyn Error>> {
    // discard CLS token, we just want patch embeddings
    let a = last_hidden_state
        .slice(1, embeddings_offset, None, 1)
        .squeeze();
    let pc = into_principal_components(&a, 3)?;

    // normalize
    let max = pc.max_dim(0, false).0;
    let min = pc.min_dim(0, false).0;
    let range = max.f_sub(&min)?;
    let pc = pc.f_sub(&min)?.f_div(&range)?;

    // arrange into input shape and put channels first
    Ok(pc.reshape([size.0, size.1, 3]).permute([2, 0, 1]))
}
